version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"